# Generated by Django 4.2.1 on 2024-02-24 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import languages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.BooleanField(default=False)),
                ('word', models.CharField(max_length=50)),
                ('pos', models.CharField(max_length=50)),
                ('usage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usage')),
                ('fields', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=languages.models.content_file_name)),
                ('fill_values', models.CharField(blank=True, max_length=200, null=True)),
                ('views', models.IntegerField(default=0)),
                ('level', models.CharField(blank=True, choices=[('a1', 'Beginner'), ('a2', 'Pre Intermediate'), ('b1', 'Intermediate'), ('b2', 'Upper Intermediate'), ('c1', 'Advanced'), ('c2', 'Proficient')], max_length=50, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('pic', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thesaurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('words', models.CharField(max_length=100, verbose_name='Words')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(blank=True, max_length=50, null=True)),
                ('word_root', models.CharField(blank=True, max_length=100, null=True)),
                ('root_pos', models.CharField(blank=True, max_length=50, null=True)),
                ('word', models.CharField(max_length=100)),
                ('pronounce', models.TextField(blank=True, null=True)),
                ('pronounce_hindi', models.TextField(blank=True, null=True)),
                ('pos', models.CharField(max_length=50)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('forms', models.TextField(blank=True, null=True)),
                ('def_inf', models.CharField(blank=True, max_length=200, null=True)),
                ('basic_definition', models.TextField(blank=True, null=True)),
                ('definition', models.TextField()),
                ('definition_hindi', models.TextField(blank=True, null=True)),
                ('definition_urdu', models.TextField(blank=True, null=True)),
                ('hindi_usage', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, default='', null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('tip', models.TextField(blank=True, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('antonyms', models.TextField(blank=True, null=True)),
                ('compare', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='dictionary/')),
                ('pic_url', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.topic')),
                ('related_post', models.ManyToManyField(blank=True, to='languages.post')),
            ],
        ),
        migrations.CreateModel(
            name='WordOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.word')),
            ],
        ),
        migrations.CreateModel(
            name='Revise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revise', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('rvcount', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.word')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='languages.topic'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('a1', 'Beginner'), ('a2', 'Pre Intermediate'), ('b1', 'Intermediate'), ('b2', 'Upper Intermediate'), ('c1', 'Advanced'), ('c2', 'Proficient')], default='', max_length=50, null=True)),
                ('pos', models.CharField(blank=True, choices=[('preposition', 'preposition'), ('helping verb', 'helping verb')], default='', max_length=50, null=True)),
                ('type', models.CharField(choices=[('fill', 'Blanks Filling'), ('choice', 'Multiple Choice')], max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('target_values', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('choice', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='languages.post')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='languages.post')),
            ],
        ),
    ]
