# Generated by Django 4.2.1 on 2024-02-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_dictionary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dictionary',
        ),
    ]
