# Generated by Django 4.2.1 on 2024-03-03 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fav',
            name='revise',
        ),
        migrations.RemoveField(
            model_name='fav',
            name='user',
        ),
        migrations.AlterField(
            model_name='fav',
            name='word',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='languages.dictionary', verbose_name='Word'),
        ),
    ]
