# Generated by Django 4.2.1 on 2024-03-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_remove_fav_created_at_remove_fav_revise_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
