# Generated by Django 4.2.1 on 2024-03-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0007_delete_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='rvdata',
            field=models.JSONField(default=dict, verbose_name='Revise Data'),
        ),
    ]
