# Generated by Django 4.2.1 on 2024-03-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0008_dictionary_rvdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='plural',
            field=models.CharField(default='', max_length=50, verbose_name='Plural Form'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='pos',
            field=models.CharField(max_length=50, verbose_name='Part of Speech'),
        ),
    ]
