# Generated by Django 4.2.1 on 2024-03-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0009_dictionary_plural_alter_dictionary_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='plural',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Plural Form'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='pos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Part of Speech'),
        ),
    ]
