# Generated by Django 4.2.1 on 2024-03-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0010_alter_dictionary_plural_alter_dictionary_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='csforms',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CS Forms'),
        ),
    ]
