# Generated by Django 4.2.1 on 2024-03-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0012_fav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
