# Generated by Django 4.2.1 on 2024-03-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0013_delete_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Word')),
                ('word_id', models.IntegerField(unique=True, verbose_name='Word PK')),
                ('rvdata', models.JSONField(default=dict, verbose_name='Revise Data')),
            ],
        ),
    ]
