# Generated by Django 4.2.1 on 2024-03-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0014_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav',
            name='word_id',
        ),
        migrations.AlterField(
            model_name='fav',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='languages.dictionary', verbose_name='Word'),
        ),
    ]
