# Generated by Django 4.2.1 on 2024-04-05 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0015_remove_fav_word_id_alter_fav_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='forms',
            field=models.JSONField(blank=True, default='[]', null=True, verbose_name='Forms'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='pronounciation',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Pronounciation'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='rvdata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Revise Data'),
        ),
        migrations.AlterField(
            model_name='fav',
            name='word',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.dictionary', verbose_name='Word'),
        ),
    ]
