# Generated by Django 4.2.1 on 2024-04-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0016_alter_dictionary_forms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='forms',
            field=models.JSONField(blank=True, default=[], null=True, verbose_name='Forms'),
        ),
    ]
