# Generated by Django 4.2.1 on 2024-04-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0017_alter_dictionary_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='forms',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Forms'),
        ),
    ]
