# Generated by Django 4.2.1 on 2024-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0018_alter_dictionary_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
