# Generated by Django 4.2.1 on 2024-04-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0020_alter_wordoftheday_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='listing',
            field=models.JSONField(default=dict),
        ),
    ]
