# Generated by Django 4.2.1 on 2024-04-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0021_dictionary_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='listing',
        ),
    ]
