# Generated by Django 4.2.1 on 2024-04-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0022_remove_dictionary_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='answer',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('fill', 'Blanks Filling'), ('mcq', 'Multiple Choice')], max_length=50),
        ),
    ]
