# Generated by Django 4.2.1 on 2024-04-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0023_remove_exercise_answer_dictionary_is_common_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='is_common',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='listing',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
