# Generated by Django 4.2.1 on 2024-04-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0024_remove_dictionary_is_common_dictionary_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='listing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
