# Generated by Django 4.2.1 on 2024-04-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0025_alter_dictionary_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='listing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
