# Generated by Django 4.2.1 on 2024-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0026_alter_dictionary_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroToHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='listing',
            field=models.IntegerField(default=0),
        ),
    ]
