# Generated by Django 4.2.1 on 2024-04-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0027_zerotohero_alter_dictionary_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerotohero',
            name='unit_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
