# Generated by Django 4.2.1 on 2024-04-29 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0028_zerotohero_unit_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='tense',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.post'),
        ),
    ]
