# Generated by Django 4.2.1 on 2024-05-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0029_exercise_answer_exercise_tense_alter_exercise_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('general_knowledge', 'GK')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(blank=True, choices=[('a1', 'A1 Beginner'), ('a2', 'A2 Pre Intermediate'), ('b1', 'B1 Intermediate'), ('b2', 'B2 Upper Intermediate'), ('c1', 'C1 Advanced'), ('c2', 'C2 Proficient')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='pos',
            field=models.CharField(blank=True, choices=[('determiner', 'determiner'), ('adverb', 'adverb'), ('preposition', 'preposition'), ('correct word', 'correct word'), ('correct form', 'correct form'), ('correct phrase', 'correct phrase'), ('usage', 'usage'), ('tag question', 'tag question'), ('helping verb', 'helping verb')], default='', max_length=50, null=True),
        ),
    ]
