# Generated by Django 4.2.1 on 2024-05-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0030_exercise_category_alter_exercise_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='choice',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(blank=True, choices=[('fill', 'Blanks Filling'), ('mcq', 'Multiple Choice')], max_length=50),
        ),
    ]
