# Generated by Django 4.2.1 on 2024-05-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0031_exercise_sub_category_alter_exercise_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='level',
        ),
        migrations.AddField(
            model_name='exercise',
            name='cefr',
            field=models.CharField(blank=True, choices=[('a1', 'A1 Beginner'), ('a2', 'A2 Pre Intermediate'), ('b1', 'B1 Intermediate'), ('b2', 'B2 Upper Intermediate'), ('c1', 'C1 Advanced'), ('c2', 'C2 Proficient')], default='', max_length=50, null=True, verbose_name='CEFR Level'),
        ),
    ]
