# Generated by Django 4.2.1 on 2024-06-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0032_remove_exercise_level_exercise_cefr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordOfTheDay',
        ),
    ]
