# Generated by Django 4.2.1 on 2024-06-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0033_delete_wordoftheday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='word',
            name='category',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
