# Generated by Django 4.2.1 on 2024-06-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0034_remove_post_topic_remove_word_category_delete_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='related_post',
        ),
        migrations.DeleteModel(
            name='Revise',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
