# Generated by Django 4.2.1 on 2024-06-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0035_remove_word_related_post_delete_revise_delete_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cefr', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
