# Generated by Django 4.2.1 on 2024-06-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0036_topicdictionary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zerotohero',
            name='unit_title',
        ),
        migrations.AddField(
            model_name='zerotohero',
            name='course',
            field=models.CharField(default='english', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zerotohero',
            name='origin',
            field=models.CharField(choices=[('english', 'English'), ('urdu', 'Urdu')], default='urdu', max_length=50),
            preserve_default=False,
        ),
    ]
