# Generated by Django 4.2.1 on 2024-06-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0037_remove_zerotohero_unit_title_zerotohero_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerotohero',
            name='origin',
            field=models.CharField(choices=[('english', 'English'), ('urdu', 'Urdu'), ('hindi', 'Hindi')], max_length=50),
        ),
    ]
