# Generated by Django 4.2.1 on 2024-06-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0038_alter_zerotohero_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerotohero',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tr', 'Turkish')], default='en', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zerotohero',
            name='origin',
            field=models.CharField(choices=[('en', 'English'), ('ur', 'Urdu'), ('hi', 'Hindi')], max_length=50),
        ),
    ]
