# Generated by Django 4.0.6 on 2024-07-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0039_zerotohero_lang_alter_zerotohero_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
