# Generated by Django 4.0.6 on 2024-07-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0041_comment_updated_at_post_topic_alter_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gk',
            name='sub_topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gk',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
