# Generated by Django 4.0.6 on 2024-07-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0042_gk_sub_topic_alter_gk_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='gk',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
