# Generated by Django 4.2.1 on 2024-03-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_learnerprofile_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='plan',
            field=models.JSONField(default={'learn': 5, 'revise': 10}, verbose_name='Plan'),
        ),
    ]
