# Generated by Django 4.2.1 on 2024-04-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_learnerprofile_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='plan',
            field=models.JSONField(default=dict, verbose_name='Plan'),
        ),
    ]
