# Generated by Django 4.2.1 on 2024-06-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.JSONField(default=dict),
        ),
    ]
