# Generated by Django 4.2.1 on 2024-06-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notes',
        ),
    ]
