# Generated by Django 4.2.1 on 2024-06-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.JSONField(default=list),
        ),
    ]
