# Generated by Django 4.2.1 on 2024-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='color',
            field=models.CharField(default='bg-light', max_length=50),
            preserve_default=False,
        ),
    ]
