# Generated by Django 4.2.1 on 2024-06-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
