# Generated by Django 4.2.1 on 2024-06-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='learnings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
